name: Test ARC Self-Hosted Runner

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]

jobs:
  # Job 1: Basic runner test
  test-runner-info:
    name: Test Runner Info
    runs-on: [self-hosted, arc, the1studio, org]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display runner information
        run: |
          echo "========================================="
          echo "🚀 ARC Runner Test Started"
          echo "========================================="
          echo ""
          echo "Runner Information:"
          echo "  Name: $RUNNER_NAME"
          echo "  OS: $RUNNER_OS"
          echo "  Architecture: $RUNNER_ARCH"
          echo "  Workspace: $GITHUB_WORKSPACE"
          echo ""
          echo "System Information:"
          uname -a
          echo ""
          echo "CPU Information:"
          lscpu | grep -E "Model name|CPU\(s\):|Thread"
          echo ""
          echo "Memory Information:"
          free -h
          echo ""
          echo "Disk Space:"
          df -h /
          echo ""

      - name: Test Docker access
        run: |
          echo "========================================="
          echo "🐳 Testing Docker Access"
          echo "========================================="
          docker --version
          docker info | grep -E "Server Version|Operating System|CPUs|Total Memory"
          echo ""
          echo "Running containers:"
          docker ps
          echo ""

      - name: Test Git
        run: |
          echo "========================================="
          echo "📦 Testing Git"
          echo "========================================="
          git --version
          git status
          echo ""

      - name: Success message
        run: |
          echo "========================================="
          echo "✅ ARC Runner Test PASSED!"
          echo "========================================="
          echo ""
          echo "This runner is ready for CI/CD workflows!"

  # Job 2-4: Parallel jobs to test auto-scaling
  parallel-test-1:
    name: Parallel Test 1
    runs-on: [self-hosted, arc, the1studio, org]
    steps:
      - run: |
          echo "Parallel job 1 running on: $RUNNER_NAME"
          sleep 30
          echo "✅ Parallel job 1 complete"

  parallel-test-2:
    name: Parallel Test 2
    runs-on: [self-hosted, arc, the1studio, org]
    steps:
      - run: |
          echo "Parallel job 2 running on: $RUNNER_NAME"
          sleep 30
          echo "✅ Parallel job 2 complete"

  parallel-test-3:
    name: Parallel Test 3
    runs-on: [self-hosted, arc, the1studio, org]
    steps:
      - run: |
          echo "Parallel job 3 running on: $RUNNER_NAME"
          sleep 30
          echo "✅ Parallel job 3 complete"
